replicaCount: 1

image:
  repository: insiderone-api
  tag: day1
  pullPolicy: Never

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

env:
  APP_VERSION: local-dev

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

ingress:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false
